// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Yq0tZNXSlJAWi1UcFs80R7LnIiY1XHg',
    appId: '1:697361902283:web:c0c0ca3d66354694bc494e',
    messagingSenderId: '697361902283',
    projectId: 'stitcher-bdfc3',
    authDomain: 'stitcher-bdfc3.firebaseapp.com',
    storageBucket: 'stitcher-bdfc3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmi3uahJ68l38L4limrlmYLiap-wXjaR4',
    appId: '1:697361902283:android:cb6a7fb4e7b54823bc494e',
    messagingSenderId: '697361902283',
    projectId: 'stitcher-bdfc3',
    storageBucket: 'stitcher-bdfc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADz9QtJY89dNVIfs2ap-p5_x2sjHbIZ8w',
    appId: '1:697361902283:ios:9a16d548e3f77af1bc494e',
    messagingSenderId: '697361902283',
    projectId: 'stitcher-bdfc3',
    storageBucket: 'stitcher-bdfc3.appspot.com',
    iosBundleId: 'com.example.sticher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADz9QtJY89dNVIfs2ap-p5_x2sjHbIZ8w',
    appId: '1:697361902283:ios:e2712e5f5f193ad0bc494e',
    messagingSenderId: '697361902283',
    projectId: 'stitcher-bdfc3',
    storageBucket: 'stitcher-bdfc3.appspot.com',
    iosBundleId: 'com.example.sticher.RunnerTests',
  );
}
